version: "3.7"

services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3308
            user: root
            password: root
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_USER: sampleuser
      MYSQL_PASSWORD: samplepassword
      MYSQL_DATABASE: sampledb
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3308:3306
    restart: unless-stopped
    volumes:
      - ./.docker/db/sample.sql:/docker-entrypoint-initdb.d/sample.sql
 
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    links:
      - mysql:mysql
    ports:
      - 8181:80
    restart: always